services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile_selenium
    environment:
      - HOST=http://127.0.0.1:5000
    shm_size: 2g
    depends_on:
      - web
    network_mode: service:web
