version: '2'

services:
  web:
    image: wst-image:v0.2
    build: .
    command: bash -c "python3 ./db_versioning/db_versioning.py --mongo mongodb://db:27017 && python3 -m web_speech_trainer $APP_CONF" 
    environment:
    - APP_CONF=${APP_CONF}
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
      - rabbitmq
      - nltk_downloader
    volumes:
      - ../database-dump:/app/dump/database-dump/
    networks:
      - network

  db:
    image: "mongo:8-noble"
    restart: always
    command:
      - '--wiredTigerCacheSizeGB=2'
    volumes:
      - ../mongo_data:/data/db
    networks:
      - network

  whisper:
    image: "onerahmet/openai-whisper-asr-webservice:v1.3.0"
    environment:
      - ASR_MODEL=${WHISPER_ASR_MODEL:-tiny}
      - ASR_ENGINE=${WHISPER_ASR_ENGINE:-openai_whisper}
    restart: always
    cpuset: ${WHISPER_CPU:-0,1}
    mem_limit: ${WHISPER_MEM_LIMIT:-5g}
    volumes:
      - whisper_models:/root/.cache/whisper
    networks:
      - network
  
  nltk_downloader:
    image: wst-image:v0.2
    command: python3 download_nltk.py
    volumes:
      - nltk_data:/root/nltk_data
    restart: no
    networks:
      - network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - network
  
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network


volumes:
  whisper_models:
  redis_data:
  nltk_data: 


networks:
  network:
    driver: bridge