FROM ubuntu:22.04
ENV LANG C.UTF-8

LABEL version="0.2"
LABEL project="wst"

RUN apt update && apt install -y software-properties-common
RUN add-apt-repository ppa:libreoffice/ppa && apt update

RUN apt install -y --no-install-recommends libgconf-2-4 libnss3 libxss1 libmagic1 python3-pip python3-dev ffmpeg exiftool inkscape mupdf mupdf-tools libmagic1 \
    nano libreoffice-impress default-jre

RUN pip3 install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip3 install --ignore-installed --no-cache-dir -r requirements.txt
