version: '2'

services:
  web:
    image: base_image
    command: bash -c "python3 ./db_versioning/db_versioning.py --mongo mongodb://db:27017 && python3 -m web_speech_trainer $APP_CONF" 
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
      - training_processor
    volumes:
      - ../database-dump:/app/dump/database-dump/

  audio_processor:
    image: base_image
    command: python3 -m audio_processor $APP_CONF
    restart: always
    depends_on:
      - db
      - whisper
      - presentation_processor

  recognized_audio_processor:
    image: base_image
    command: python3 -m recognized_audio_processor $APP_CONF
    restart: always
    depends_on:
      - db
      - audio_processor
      - presentation_processor

  presentation_processor:
    image: base_image
    build: .
    command: python3 -m presentation_processor $APP_CONF
    restart: always
    depends_on:
      - db

  recognized_presentation_processor:
    image: base_image
    command: python3 -m recognized_presentation_processor $APP_CONF
    restart: always
    depends_on:
      - db
      - presentation_processor

  training_processor:
    image: base_image
    command: python3 -m training_processor $APP_CONF
    restart: always
    depends_on:
      - db
      - recognized_audio_processor
      - recognized_presentation_processor

  task_attempt_to_pass_back_processor:
    image: base_image
    command: python3 -m task_attempt_to_pass_back_processor $APP_CONF
    restart: always
    depends_on:
      - db

  db:
    image: "mongo:4.4.1"
    restart: always
    command:
      - '--wiredTigerCacheSizeGB=2'
    volumes:
      - ../mongo_data:/data/db

  whisper:
    image: "onerahmet/openai-whisper-asr-webservice:v1.3.0"
    environment:
      - ASR_MODEL=${WHISPER_ASR_MODEL:-tiny}
      - ASR_ENGINE=${WHISPER_ASR_ENGINE:-openai_whisper}
    restart: always
    cpuset: ${WHISPER_CPU:-0,1}
    mem_limit: 5g
    volumes:
      - ./whisper_asr_model_cache:/root/.cache/whisper