FROM ubuntu:18.04
ENV LANG C.UTF-8
RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get install -y  libgconf2-4 libnss3 libxss1 python3-pip vim ffmpeg exiftool inkscape mupdf mupdf-tools wget unzip
WORKDIR /usr/local/bin
RUN wget https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
RUN unzip chromedriver_linux64.zip
RUN wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_90.0.4430.72-1_amd64.deb
RUN apt-get install -y ./google-chrome-stable_90.0.4430.72-1_amd64.deb
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools

