version: '2'

services:
  flower:
    image: wst-image:v0.2
    command: celery -A app.celery_app flower --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD} --broker_api=http://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:15672/api/
    ports:
      - "5555:5555"
    environment:
      - APP_CONF=${APP_CONF}
      - FLOWER_USER=${FLOWER_USER}
      - FLOWER_PASSWORD=${FLOWER_PASSWORD}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - celery_worker_audio_rec
      - celery_worker_audio_proc
      - celery_worker_pres_rec
      - celery_worker_pres_proc
      - celery_worker_training
      - celery_worker_passback
      - celery_worker_default
    restart: always
    networks:
      - wst_network

  celery_worker_audio_rec:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q audio_recognition
    environment:
      - APP_CONF=${APP_CONF}
    networks:
      - wst_network

  celery_worker_audio_proc:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q audio_processing
    environment:
      - APP_CONF=${APP_CONF}
    networks:
      - wst_network

  celery_worker_pres_rec:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q presentation_recognition
    environment:
      - APP_CONF=${APP_CONF}
    volumes:
      - nltk_data:/root/nltk_data
    networks:
      - wst_network

  celery_worker_pres_proc:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q presentation_processing
    environment:
      - APP_CONF=${APP_CONF}
    networks:
      - wst_network

  celery_worker_training:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q training
    environment:
      - APP_CONF=${APP_CONF}
    volumes:
      - nltk_data:/root/nltk_data
    networks:
      - wst_network

  celery_worker_passback:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q passback
    environment:
      - APP_CONF=${APP_CONF}
    networks:
      - wst_network

  celery_worker_default:
    image: wst-image:v0.2
    command: celery -A app.celery_app worker --loglevel=info --concurrency=1 -Q default
    environment:
      - APP_CONF=${APP_CONF}
    networks:
      - wst_network

volumes:
  nltk_data:
    external: true
    name: web_speech_trainer_nltk_data


networks:
  wst_network:
    external: true
    name: web_speech_trainer_network