services:
  web:
    build: .
    command: python -m web_speech_trainer
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mongo:4.4.1"
    restart: always

