class TrainingStatus:
    NEW = "NEW"
    SENT_FOR_PREPARATION = "SENT_FOR_PREPARATION"
    PREPARING = "PREPARING"
    PREPARED = "PREPARED"
    PREPARATION_FAILED = "PREPARATION_FAILED"
    SENT_FOR_PROCESSING = "SENT_FOR_PROCESSING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class AudioStatus:
    NEW = "NEW"
    SENT_FOR_RECOGNITION = "SENT_FOR_RECOGNITION"
    RECOGNIZING = "RECOGNIZING"
    RECOGNIZED = "RECOGNIZED"
    RECOGNITION_FAILED = "RECOGNITION_FAILED"
    SENT_FOR_PROCESSING = "SENT_FOR_PROCESSING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PROCESSING_FAILED = "PROCESSING_FAILED"


class PresentationStatus:
    NEW = "NEW"
    SENT_FOR_RECOGNITION = "SENT_FOR_RECOGNITION"
    RECOGNIZING = "RECOGNIZING"
    RECOGNIZED = "RECOGNIZED"
    RECOGNITION_FAILED = "RECOGNITION_FAILED"
    SENT_FOR_PROCESSING = "SENT_FOR_PROCESSING"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
