name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Build system images (non-pulling)
      run: scripts/build_system_image.sh
      shell: bash

    - name: Build docker-compose
      run: |
        docker-compose build

    - name: Run docker-compose
      run:
        APP_CONF=../app_conf/testing.ini docker-compose up -d

    - name: Run tests
      run: |
        docker ps -a
        docker-compose logs
        docker exec web_speech_trainer_web_1 bash -c 'cd /app/tests && pytest .'
