name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Build system images (non-pulling)
      run: |
        # build base image
        docker build -f Dockerfile_base -t osll/wst-base:v0.2 .

    - name: Decreasing whisper model for tests
      run: |
        cp docker-compose.yml docker-compose-tmp.yml
        sed -e "s/ASR_MODEL=medium/ASR_MODEL=tiny/" docker-compose-tmp.yml > docker-compose.yml
        rm docker-compose-tmp.yml

    - name: Build docker-compose
      run: |
        docker-compose build

    - name: Run docker-compose
      run:
        APP_CONF=../app_conf/testing.ini docker-compose up -d

    - name: Run tests
      run: |
        docker ps -a
        docker-compose logs
        docker-compose exec web bash -c 'cd /project/tests && pytest .'
