name: Selenium_tests

on: pull_request

jobs:
  check_tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build and run docker compose with docker-compose-selenium (tests)
        run: |
          make build-base
          make tests

      - name: Run check tests (tests)
        run: |
          make check-tests
